#!/usr/bin/env bash

OUT=target/invoke.out


aws lambda invoke \
  --function-name project-qa-callculon \
  --cli-binary-format raw-in-base64-out \
  --payload "$(jq -c . ${1:-payload.json})" \
  $OUT

jq . $OUT
